name: 'Hello World - congnc6'
description: 'Wait a designated number of milliseconds'
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: cong
  repo:
    description: 'repo'
    required: true
    default: https://github.com/gabyshev/testapp
  apps:
    description: 'apps'
    required: true
    default: testapp
    
outputs:
  time: 
    description: 'the greeting time'

runs:
  using: 'node16'
  main: 'dist/index.js'